#!/bin/bash

source $(dirname $0)/common.sh

nav=_data/$autogen/navigation.yml
mkdir -pv $(dirname $nav)
nav=$(realpath $nav)

plan=md/$autogen/plan.md
mkdir -pv $(dirname $plan)
plan=$(realpath $plan)

plan_hidden=.plan

I="  "

_find(){
    find $1 -mindepth 1 -maxdepth 1 ${@:2} \
    | xargs awk '
        FNR==1 {
            order[FILENAME] = 999;
        }
        /order/ {
            order[FILENAME] = $2;
        }
        END {
            for (f in order)
                print order[f], f
        }' \
    | sort -g | cut -d ' ' -f 2-
}

_grep() { grep $@ || test $? = 1; }
_field() { _grep $@ | cut -d ' ' -f 2-; }

process(){
    local folder=$1
    local depth=$2
    local indent=$(printf "$I%.0s" $(seq $depth))

    _find $folder -type f | while read file
    do
        include=$(_field navigation $file)
        if [ "$include" == "false" ]
        then
            continue
        fi

        link=$(_field permalink $file)
        [ -z $link ] && link=/$(sed 's/md$/html/' <<< $file)

        name=$(_field label $file)
        [ -z "$name" ] && name=$(_field title $file)
        if [ -z "$name" ]
        then
            echo "No title for $file"
            exit 1
        fi

        hidden=$(_field hidden $file)
        if [ "$hidden" != "true" ]
        then
            echo "$indent[F] $file"
            echo "$indent- name: $name" >> $nav
            echo "$indent  link: $link" >> $nav
            echo >> $nav

            echo "$indent* [$name]($link)" >> $plan

            subfolder=${file%.*}
            if [ -d "$subfolder" ]
            then
                echo "${indent}  submenu:" >> $nav
                echo >> $nav

                process $subfolder $((depth+1))
            fi
        else
            echo "* [$name]($link)" >> $plan_hidden
        fi
    done
}


echo "# $(date)" > $nav
echo "# Autogenerated file" >> $nav
echo >> $nav
echo "- name: Home" >> $nav
echo "  link: /" >> $nav
echo >> $nav
echo "  submenu:" >> $nav
echo >> $nav

echo "<!-- $(date) -->" > $plan
echo "<!-- Autogenerated file -->" >> $plan
echo >> $plan
echo "## Indexed pages" >> $plan
echo "* [Home](/)" >> $plan

process $sources 2

if [ -f "$plan_hidden" ]
then
    echo >> $plan
    echo "## Unreferenced pages" >> $plan
    cat $plan_hidden >> $plan
    rm $plan_hidden
fi

echo
# cat $nav
cat $plan
