#!/bin/bash

source $(dirname $0)/common.sh
out=_data/$outdir/navigation.yml
mkdir -pv $(dirname $out)
out=$(realpath $out)
I="  "

_find(){
    find $1 -mindepth 1 -maxdepth 1 ${@:2} \
    | xargs awk '/order/{print $2, FILENAME; found=1}END{if (found == 0) {print 999, FILENAME}}' \
    | sort -g | cut -d ' ' -f 2-
}

_grep() { grep $@ || test $? = 1; }
_field() { _grep $@ | cut -d ' ' -f 2-; }


process(){
    local folder=$1
    local depth=$2
    local indent=$(printf "$I%.0s" $(seq $depth))

    _find $1 -type f | while read file
    do
        include=$(_field navigation $file)
        if [ "$include" == "false" ]
        then
            continue
        fi

        link=$(_field permalink $file)
        [ -z $link ] && link=/$(sed 's/md/html/' <<< $file)

        name=$(_field title $file)
        if [ -z "$name" ]
        then
            echo "No title for $file"
            exit 1
        fi

        echo "$indent[F] $file"
        echo "$indent- name: $name" >> $out
        echo "$indent  link: $link" >> $out
        echo >> $out

        subfolder=${file%.*}
        if [ -d "$subfolder" ]
        then
            echo "${indent}  submenu:" >> $out
            echo >> $out
            process $subfolder $((depth+1))
        fi
    done
}


echo "# $(date)" > $out
echo "# Autogenerated file" >> $out
process src 1

echo
cat $out
